name: Basic-CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    paths:
      - 'basic/**'

env:
  IMAGE_ML_APP: hello-wyatt

jobs:
  ci-test-bash-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test echo
        run: |
          echo 'test'

      - name: Test ls
        run: |
          ls -all .

  build-docker-but-with-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login
        run: |
          docker login ghcr.io -u kytewy -p ${{ secrets.GH_TOKEN }}

      - name: Build
        run: |
          docker build --tag ghcr.io/kytewy/hello-wyatt:latest ./basic

      - name: Push
        run: |
          docker push ghcr.io/kytewy/hello-wyatt:latest

      - name: Run ok
        run: |
          docker run --rm --name wyatt-test-run ghcr.io/kyryl-opens-ml/hello-wyatt:latest
